catalog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from catalog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my_borrowed')
]

locallibrary/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls'))
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls'))

]

catalog/models.py
import uuid
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre.")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book.")
    isbn = models.CharField(max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[0:3]])

    display_genre.short_description = 'Genre'


class BookIstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique id for this particular book across whole library.')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_died = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import generic

from catalog.models import Book, BookIstance, Author, Genre


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookIstance.objects.all().count()
    num_genres = Genre.objects.count()
    num_instances_available = BookIstance.objects.filter(status__exact='a').count()
    num_authors = BookIstance.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = 1
    return render(request, 'index.html', context={'num_books': num_books, 'num_instances': num_instances,
                                                  'num_instances_available': num_instances_available,
                                                  'num_authors': num_authors,
                                                  'num_genres': num_genres, "num_visits": num_visits})


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        ctx = super(AuthorDetailView, self).get_context_data(**kwargs)
        ctx['book'] = Book.objects.all()
        return ctx


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookIstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookIstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Author : {{ author.first_name }},{{ author.last_name }}</h1>
        <p>{{ author.date_of_birth }} - {{ author.date_of_died }}</p>
    <h3>Books:</h3>
        <ul>

            {% for x in book.all %}
                {% if author.id == x.id %}
                <li><a href ="{{ x.get_absolute_url }}">{{x.title}}</a></li>
                    <p>{{ x.summary|slice:":200" }}</p>
                {% endif %}
            {% endfor %}
        </ul>

    </div>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h1><strong>Author List</strong></h1>
        {% if author_list %}
            <ul>
         {% for author in author_list %}
             <li><a href ='{{ author.get_absolute_url }}'>{{ author }} ({{author.date_of_birth}}-{{ author.date_of_died }})</a></li>
            {% endfor %}
            </ul>
         {% else %}
         <p>There not authors in this library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Title : {{ book.title }}</h1>
    <p><strong>Author:</strong><a href="">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {% for genre in book.genre.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <div style="margin-left: 20px;margin-top: 20px">
        <h4>Coppies</h4>
        {% for copy in book.bookistance_set.all %}
                <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
         {% endfor %}
    </div>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Book List</h1>
    {% if book_list  %}
        <ul>
        {% for book in book_list %}
            <li>
            <a href = "{{ book.get_absolute_url }}">{{ book.title }}</a>({{ book.author }}
            </li>
        {% endfor %}
        </ul>
        {% else %}
        <p>There no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Borrowed Books</h1>
     {% if bookistance_list %}
    <ul>
     {% for books in bookistance_list %}
     <li class = "{% if books.is_overdue  %} text-danger {% endif %}">
     <a href = "{% url 'book-detail' books.book.pk %}"> {{ books.book.title }}</a> {{ books.due_back }}
     </li>
    {% endfor %}

     </ul>
    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block title %}<title> Local Library </title>{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>


<body>
    <div class="container-fluid">
        <div class = "row">
            <div class = "col-sm-2">
                {% block sidebar %}
                    <ul class ="sidebar-nav">
                    <li><a href = "{% url 'index' %}">Home</a></li>
                    <li><a href = "{% url 'books' %}">All books</a></li>
                    <li><a href = "{% url 'authors' %}">All authors</a></li>
                    {% if user.is_authenticated %}
                    <li><a href =" {% url 'my_borrowed' %}">My Borrowed Books</a></li>
                    <li>{{ user.get_username }}</li>

                    <li><a href ="{% url 'logout' %}?next={{request.path}}">Log in out</a></li>
                    {% else %}
                    <li><a href ="{% url 'login' %}?next={{request.path}}">Login</a></li>
                    {% endif %}
                    </ul>
                {% endblock %}
            </div>
        <div class="col-sm-10">
            {% block content %} {% endblock %}
        {% block pagination %}
            {% if is_paginated %}
                <div class = "pagination">
                    <span class = "page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                         {% if page_obj.has_next %}
                             <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        {% endblock %}
        </div>
        </div>
    </div>

</body>
</html>

templates/index.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Local Library Home</h1>
        <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example.</p>

    <h2>Dynamic content</h2>

        <p>The library has the following records counts:</p>
        <ul>
            <li><strong>Books:</strong> {{ num_books }}</li>
            <li><strong>Copies:</strong> {{ num_instances }}</li>
            <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
            <li><strong>Genres:</strong> {{ num_genres }}</li>
            <li><strong>Authors:</strong> {{ num_authors }}</li>
            <li><strong>Visits Site:</strong> {{ num_visits }}</li>
        </ul>

{% endblock %}